import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header/Header";
import Copering from "@/components/Copering";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body
        className='bg-neutral-950 antialiased'
      >
        <Header />
        {children}
        <Copering />
      </body>
    </html>
  );
}
